name:                sudoku
version:             0.1.0.0
github:              "gavinleroy/FP-Studio/sudoku"
license:             BSD3
author:              "Gavin Gray"
maintainer:          "gavinleroy6@gmail.com"
copyright:           "Gavin Gray"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gavinleroy/FP-Studio/sudoku#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- vector
- random
- random-shuffle

library:
  source-dirs: src

executables:
  sudoku:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O3
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sudoku

tests:
  sudoku-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sudoku
